# Page settings
baseurl = "http://greencaps.rocks/"
title = "Green caps - geeks ready to rescue your project"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  # Meta
  author = "Green caps"
  description = "Green caps - geeks for the rescue of your project"
  keywords = "Ruby on Rails development,Front-end development,Microservices,HTML&CSS layout,Web design,RoR team,React.js,Node.js,Docker"
  email = "info@greencaps.rocks"
  # Navigation
  [params.navigation]
    brand = "Green caps"
    home = "Home"
    work = "Portfolio"
    services = "Technologies"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    subtitle = '<br />Geeks wearing silly green caps are going to rescue your project. <br /> Beware!'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = 'This is not all our projects. To see full list, visit <a href="/portfolio/">portfolio</a>.'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Services section
  [params.services]
    enable = true
    title = "Technologies"
    description = "We are using bleeding edge Open Source technologies in our work."

    [[params.services.item]]
      title = "Back-End"
      description = "We use <span class='ruby-lang'>Ruby</span> and <span class='ror-lang'>Ruby On Rails</span> for most of our projects. However, when it is not enough - when we need really high perfomance - we add <span class='go-lang'>Go</span> to the mix."
      icon = "icon-layers"

    [[params.services.item]]
      title = "Front-end"
      description = "<span class='react-lang'>React</span> with <span class='redux-lang'>Redux</span> is the our JavaScript framework. We use <span class='node-lang'>Node.js</span> and <span class='es6-lang'>ES6</span>, the latest version of JavaScript, for our front-end development."
      icon = "icon-screen-desktop"

    [[params.services.item]]
      title = "Mobile"
      description = "Though we use conventional <span class='swift-lang'>Swift</span> for iOS development and <span class='java-lang'>Java</span> for Android development, we also can use <span class='xamarin-lang'>Xamarin</span> and <span class='ionic-lang'>Ionic</span> if it suits best for your project."
      icon = "icon-screen-smartphone"

    [[params.services.item]]
      title = "Infrastructure"
      description = "We are using <span class='docker-lang'>Docker</span> for containerization, <span class='aws-lang'>Amazon Web services</span> as a platform and <span class='ansible-lang'>Ansible</span> to automate infrastracture management."
      icon = "icon-wrench"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Contact section
  [params.contact]
    enable = true
    title = "Get in touch"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-skype", "esherkunov"],
        ["icon-phone", "(999) 999 99 99"],
        ["icon-envelope", "info@greencaps.rocks"],
        ["icon-globe", '<a href="http://greencaps.rocks/" target="_blank">greencaps.rocks</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Green caps'
